project_id = "bgfjhietjsrlzscxdutt"

[functions.ai-insights]
verify_jwt = false

[functions.validate-email-ai]
verify_jwt = false

[functions.api-assistant]
verify_jwt = false

[functions.validate-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.purchase-credits]
verify_jwt = false
